version: "3.8"

services:
  db:
    container_name: rss-db
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - rss-db-data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: rss-db
    restart: always
  server:
    container_name: rss-server
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8080:8080
volumes:
  rss-db-data:
