version: "3.8"

services:
  db:
    container_name: rss-db
    image: postgres:15-alpine
    volumes:
      - rss-db-data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: rss-db

volumes:
  rss-db-data:
